### PR TITLE
Feature/auth handling

### PR DESCRIPTION
**Pull request by natelo**
Note that solutions for win was a bit updated.. you will need to set user macros for RTCWBASE and RTCW_MOD_NAME .. 
To do that;
Click Property Manager (window/tab) -> click on "wolf" -> Then "Debug | win32" -> Then "Microsoft.,Cpp.Win32.user" and once window opens, click under "Common Properties" on "User Macros" and "Add Macro". 
Name should be RTCWBASE and RTCW_MOD_NAME and values set to whatever or however you have it set.

Explanation
- RTCWBASE should point to root of your game folder, one you use for testing stuff
Example: _E:\Pub\Projects\Return to Castle Wolfenstein 1.4_
- RTCW_MOD_NAME should be the name of the mod folder ( one set in fs_game) 
Example: _rtcwProDev_
- Ensure that there's a mp_bin.pk3 pack inside mod folder as bin's get inserted there as well.

This two variables are used for dumping bins upon build and updating default pack as well as for debugging.

### CODE REVIEW

**Comment by krazykaze81** [comment]
I'll try to review this later - shouldn't this be for 1.2 milestone?

**Comment by wolf6542** [comment]
Can't compile. Asks for botlib.lib, but it's in its supposed place already?

**Comment by natelo** [comment]
Yep. Make sure you have a clean branch and issue recompile.

**Comment by natelo** [comment]
Need this stuff for cvar restrictions thus merged it.

**Pull request merged**
